version: '3.8'

services:
  metabase:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase
      - MB_DB_HOST=db
    depends_on:
      - db
    volumes:
      - ./configs/.env:/app/.env

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase
      - POSTGRES_DB=metabase
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 